# Generated by Django 2.1.2 on 2018-12-13 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Automovil', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='automovil',
            name='anio',
            field=models.CharField(default='2018', max_length=4),
        ),
    ]
